# Browsersync config
BROWSERSYNC:
  # URL of local development server goes here (ex. http://localsite.dev)
  url: ""

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"

# Set to true if you want static asset revisioning, helpful for cache busting
REVISIONING: false    

RELEASE:
  type: 'theme'
  languagesDir: './languages/'
  files:
    - "./**/*.*"
    - "!./**/*.map"
    - "!./**/build/**/*.*"
    - "!./**/.git/**"
    - "!./**/.gitignore"
    - "!./**/.gitmodules"
    - "!./**/gulpfile.js"
    - "!./**/gruntfile.js"
    - "!./**/gulp/**/*.*"
    - "!./**/package.json"
    - "!./**/package-lock.json"
    - "!./**/bower.json"
    - "!./**/composer.json"
    - "!./**/node_modules/**/*.*"
    - "!./**/bower_components/**/*.*"
    - "!./**/README.md"
    - "!./**/*.zip"
    - "!./**/config-default.yml"
    - "!./**/gulpfile.babel.js"
    - "!./**/.babelrc"
    - "!./**/config.yml"
    - "!./**/webpack.config.js"